package org.cakephp.netbeans.ui.wizards;

import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;

public final class DatabaseConfigurationVisualPanel extends JPanel {
	private static final long serialVersionUID = -9027538981324023703L;

	/** Creates new form CakeDBConfigurationVisualPanel1 */
	public DatabaseConfigurationVisualPanel() {
		initComponents();
	}

	@Override
	public String getName() {
		return "Database Configuration";
	}
	
	public JTextField getNameField(){
		return nameTextField;
	}

	public JList getDriverList(){
		return driverList;
	}
	
	public void setDriverList(String[] strArray){
		driverList.setListData(strArray);
	}

	public JCheckBox getPersistentCheckBox(){
		return persistentCheckBox;
	}

	public JTextField getHostField(){
		return hostTextField;
	}

	public JTextField getPortField(){
		return portTextField;
	}

	public JTextField getUserField(){
		return userTextField;
	}

	public JTextField getPasswordField(){
		return passwordTextField;
	}

	public JTextField getDatabaseNameField(){
		return databaseNameTextField;
	}

	public JTextField getPrefixField(){
		return prefixTextField;
	}

	public JTextField getEncodingField(){
		return encodingTextField;
	}
	
	@Override
	public void validate(){
		
	}
	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        driverLabel = new javax.swing.JLabel();
        persistentLabel = new javax.swing.JLabel();
        hostLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        databaseNameLabel = new javax.swing.JLabel();
        prefixLabel = new javax.swing.JLabel();
        encodingLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        hostTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        userTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        databaseNameTextField = new javax.swing.JTextField();
        prefixTextField = new javax.swing.JTextField();
        encodingTextField = new javax.swing.JTextField();
        nameDefaultLabel = new javax.swing.JLabel();
        hostDefaultLabel = new javax.swing.JLabel();
        userDefaultLabel = new javax.swing.JLabel();
        databaseNameDefaultLabel = new javax.swing.JLabel();
        persistentCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverList = new javax.swing.JList();

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.nameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(driverLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.driverLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(persistentLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.persistentLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(hostLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.hostLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(portLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.portLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(userLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.userLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.passwordLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(databaseNameLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.databaseNameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(prefixLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.prefixLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(encodingLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.encodingLabel.text")); // NOI18N

        nameTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.nameTextField.text")); // NOI18N

        hostTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.hostTextField.text")); // NOI18N

        portTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.portTextField.text")); // NOI18N

        userTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.userTextField.text")); // NOI18N

        passwordTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.passwordTextField.text")); // NOI18N
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        databaseNameTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.databaseNameTextField.text")); // NOI18N

        prefixTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.prefixTextField.text")); // NOI18N

        encodingTextField.setText(org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.encodingTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nameDefaultLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.nameDefaultLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(hostDefaultLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.hostDefaultLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(userDefaultLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.userDefaultLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(databaseNameDefaultLabel, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.databaseNameDefaultLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(persistentCheckBox, org.openide.util.NbBundle.getMessage(DatabaseConfigurationVisualPanel.class, "DatabaseConfigurationVisualPanel.persistentCheckBox.text")); // NOI18N

        driverList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(driverList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(driverLabel))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameDefaultLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(persistentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(persistentCheckBox))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hostLabel)
                                    .addComponent(portLabel)
                                    .addComponent(userLabel)
                                    .addComponent(passwordLabel)
                                    .addComponent(databaseNameLabel)
                                    .addComponent(prefixLabel)
                                    .addComponent(encodingLabel))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encodingTextField)
                                    .addComponent(prefixTextField)
                                    .addComponent(databaseNameTextField)
                                    .addComponent(passwordTextField)
                                    .addComponent(portTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(userTextField)
                                    .addComponent(hostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostDefaultLabel)
                            .addComponent(userDefaultLabel)
                            .addComponent(databaseNameDefaultLabel))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDefaultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driverLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persistentLabel)
                    .addComponent(persistentCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostLabel)
                    .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostDefaultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDefaultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseNameLabel)
                    .addComponent(databaseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(databaseNameDefaultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixLabel)
                    .addComponent(prefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encodingLabel)
                    .addComponent(encodingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_passwordTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel databaseNameDefaultLabel;
    private javax.swing.JLabel databaseNameLabel;
    private javax.swing.JTextField databaseNameTextField;
    private javax.swing.JLabel driverLabel;
    private javax.swing.JList driverList;
    private javax.swing.JLabel encodingLabel;
    private javax.swing.JTextField encodingTextField;
    private javax.swing.JLabel hostDefaultLabel;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JTextField hostTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameDefaultLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JCheckBox persistentCheckBox;
    private javax.swing.JLabel persistentLabel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JLabel prefixLabel;
    private javax.swing.JTextField prefixTextField;
    private javax.swing.JLabel userDefaultLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
